(setq sys::*libtk-pathname* "-lXm -lXpm -lXext -lXp")
(setq sys::*libxt-pathname* "-lXt")
(setq sys::*libx11-pathname* "-lX11")
(setq sys::*libwnn-pathname* "libwnn.a")
(excl:set-case-mode :case-insensitive-upper)
(pushnew :clim-dont-load-patches *features*)
(load "misc/compile-1.lisp")
(declaim (optimize (speed 3) (debug 1) (safety 1)))
(setq *compile-print* t)
(setq *compile-verbose* t)
(setq excl::*warn-smp-usage* nil)
(setq excl:*redefinition-warnings* t)
(setq excl:*record-source-file-info* t)
(setq comp:save-local-names-switch t)
(setq comp:save-source-level-debug-info-switch t)
(setq excl:*load-local-names-info* t)
(setq excl:*load-source-file-info* t)
(setq excl:*record-xref-info* t)
(setq excl:*load-xref-info* t)
(setf (sys:gsgc-switch :print) t)
(compile-it (quote motif-clim))
(exit 0)
