
* The Common Lisp Interface Manager

** Description
   The contents of this repo are known to compile and work in Allegro
   CL 8.2 and later.  No work has been done to make it work on other
   Common Lisps, even though there is considerable conditionalization
   for many other CLs.

   See the file LICENSE for information on the license for this source
   code.

** Compiling Express Allegro on linux-86
   1. makefile.defs to parent folder
   2. Create a file: makefile.top in the parent folder.
      touch ../makefile.top
   3. Edit Makefile.defs, LISP should point to your allegro lisp, e.g. /home/me/bin/alisp.
   4. Copy Makefile.defs to parent directory.
   5. Build with make, setting the hosd environment variable.
      export HOST=linux; make
   6. You make need to run the make twice (or more) due to the fact
      that Allegro only allows you to use a restricted amount of
      garbage collection.

** quicklisp
   The easiest way to load things is by quicklisp

   1. cd ~/bin
   2. ln -s ~/acl100express/bin/alist .
   3. cd ~/quickload/local-projects
   4. ln -s ~/clim2 .
   5. rm system-index.txt
   6. cd ~/clim2
   7. alist
   8. (ql:quickload :clim2)

      You may need to run this multiple times

** Testing

   1. start up alegro, e.g.
      alisp
   2. (load "load-clim")
   3. (load "clim-example")

   
