
* The Common Lisp Interface Manager


** Description


   The contents of this repo are known to compile and work in Allegro
   CL 8.2 and later.  No work has been done to make it work on other
   Common Lisps, even though there is considerable conditionalization
   for many other CLs.

   See the file LICENSE for information on the license for this source
   code.


** Install build envirenment and package dependancies

   sudo apt-get install build-essential 
   sudo apt-get install libmotif-dev
   sudo apt-get install libxp-dev


** Files to add to path
   ln -s ~/dev/common-lisp/acl100express/src/runlisp.sh .

** Compiling Express Allegro on linux-86
   1. makefile.defs to parent folder
   2. Create a file: makefile.top in the parent folder.
      touch ../makefile.top
   3. Edit Makefile.defs
      LISP should point to your allegro lisp, e.g. /home/me/bin/alisp.
      DCL shold point to your allegro lisp image.  If you're using
      Allegro Express something like: alisp.dxl
   4. Copy Makefile.defs to parent directory.
   5. Build with make, setting the hosd environment variable.
      export HOST=linux; make
   6. You make need to run the make twice (or more) due to the fact
      that Allegro only allows you to use a restricted amount of
      garbage collection.
   7. 




** Testing

   1. start up alegro, e.g.
      alisp
   2. (load "load-clim")
   3. (load "clim-example")

   

