
* The Common Lisp Interface Manager

** Description
   The contents of this repo are known to compile and work in Allegro
   CL 8.2 and later.  No work has been done to make it work on other
   Common Lisps, even though there is considerable conditionalization
   for many other CLs.

   See the file LICENSE for information on the license for this source
   code.

** Compiling: Express Allegro on linux-86
   This is currently the only configuration supported.  Most build
   code supporting other platforms has been removed in an attempt to
   simplify the build process and migrate it to asdf.
   1. Edit Makefile, LISP should point to your allegro lisp, e.g. ~/bin/alisp.
   2. CL should point to your base alegro image files, e.g. ~/bin/alisp.dxl
      
   3. From the command line:
      export HOST=linux; make
   4. You may need to run the make twice (or more times) due to the
      fact that Allegro only allows you to use a restricted amount of
      garbage collection.

** quicklisp
   The easiest way to load things is by quicklisp

   1. cd ~/bin
   2. ln -s ~/acl100express/bin/alist .
   3. cd ~/quickload/local-projects
   4. ln -s ~/clim2 .
   5. rm system-index.txt
   6. cd ~/clim2
   7. alist
   8. (ql:quickload :clim2)

      You may need to run this multiple times

** Testing

   1. start up alegro, e.g.
      alisp
   2. (load "load-clim")
   3. (load "clim-example")

   
