
* The Common Lisp Interface Manager

** Description
   The contents of this repo are known to compile and work with the
   latest version of Allegro Express.  The short term goal is to get
   thing to work with SBCL.

   See the file LICENSE for information on the license for this source
   code.  Note that newer files may also copywrited under the MIT
   copywrite.  Those files are noted specifically in the file header.

** Compilation Dependancies: Express Allegro and Ubuntu x86-32
   Install Expresss Allegro on Ubuntu x86-32 12.04.  Add alisp to the
   path using something like the following:

   1. cd ~/bin
   2. ln -s ~/acl100express/bin/alist .
   3. ln -s ~/acl100express/bin/alisp.dxl .

** Install Motif
   You'll also need to install the motif toolkit and build essentials.
   Something like:

   1. sudo apt-get install libmotif-dev
   2. sudo apt-get libxt-dev
   3. sudo apt-get install build-essential

** Build motif wraper
   1. cd ~/clim2/c-src
   2. make

** Install quicklisp
   The easiest way to load things is by quicklisp.  First install
   quicklisp from the quicklisp website, configuring it for you
   Allegro Express configuraiton.  Then link clim2

   1. cd ~/quickload/local-projects
   2. ln -s ~/clim2 .
   3. rm system-index.txt
   4. cd ~/clim2
   5. alist
   6. (ql:quickload :clim2)
   7. (clim-demo:start-demo)

** Testing
   (not currently operable.)
   1. start up alegro, e.g.
      alisp
   2. (load "load-clim")
   3. (load "clim-example")

   
